<Project Sdk="Microsoft.NET.Sdk">

  <!--
    INFRAESTRUCTURA: detalles técnicos (EF Core, ficheros, correo, APIs externas...).
    Implementa las interfaces que define la capa de Aplicación.
  -->

  <ItemGroup>
    <ProjectReference Include="..\GestorIncidencias.Application\GestorIncidencias.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
  </ItemGroup>

</Project>
